version: '3'
services:
    php-apache:
        build:
            context: ./php-apache
            args:
                - UID=${UID} 
                - GID=${GID}
                - USERNAME=${USERNAME}
        ports:
            - 80:80
        volumes:
            - ./app:/var/www/html
        links:
            - 'mariadb'
        environment:
            - APACHE_RUN_USER=${USERNAME}
            - APACHE_RUN_GROUP=#${GID}
    mariadb:
        image: mariadb:10.1
        volumes:
            - rkt_mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/London"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'
    dbadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - 'mariadb'
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: rootpwd
volumes:
    rkt_mariadb:

